org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.235
loader_version_range=[4,)

mod_id=advancedtools
mod_name=AdvancedTools
mod_license=All Rights Reserved
mod_version=1.21.1-3.0.0-alpha.1
mod_group_id=dev.ssscfw.advancedtools
