package dev.ssscfw.advancedtools.client;

import com.mojang.blaze3d.platform.InputConstants;
import dev.ssscfw.advancedtools.AdvancedTools;
import dev.ssscfw.advancedtools.item.MagnetItem;
import dev.ssscfw.advancedtools.network.ToggleMagnetPayload;
import net.minecraft.client.Minecraft;
import net.minecraft.client.player.LocalPlayer;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.client.event.ClientTickEvent;
import net.neoforged.neoforge.network.PacketDistributor;
import org.lwjgl.glfw.GLFW;

@EventBusSubscriber(modid = AdvancedTools.MOD_ID, value = Dist.CLIENT)
public final class ClientGameEvents {
    private static boolean fWasDown;

    private ClientGameEvents() {
    }

    @SubscribeEvent
    public static void onClientTick(ClientTickEvent.Pre event) {
        Minecraft minecraft = Minecraft.getInstance();
        LocalPlayer player = minecraft.player;
        if (player == null || minecraft.screen != null || !minecraft.isWindowActive()) {
            fWasDown = false;
            return;
        }

        boolean fDown = InputConstants.isKeyDown(minecraft.getWindow().getWindow(), GLFW.GLFW_KEY_F);
        if (fDown && !fWasDown && isHoldingMagnet(player)) {
            // F is vanilla's default swap-offhand key. Consume its pending click so the magnet toggle
            // does not also move the item between hands.
            while (minecraft.options.keySwapOffhand.consumeClick()) {
                // consume all clicks generated by this press
            }
            PacketDistributor.sendToServer(ToggleMagnetPayload.INSTANCE);
        }
        fWasDown = fDown;
    }

    private static boolean isHoldingMagnet(LocalPlayer player) {
        return player.getMainHandItem().getItem() instanceof MagnetItem
                || player.getOffhandItem().getItem() instanceof MagnetItem;
    }
}
