package dev.ssscfw.advancedtools.client;

import com.mojang.blaze3d.platform.InputConstants;
import dev.ssscfw.advancedtools.AdvancedTools;
import dev.ssscfw.advancedtools.item.MagnetItem;
import dev.ssscfw.advancedtools.item.SolidifierItem;
import dev.ssscfw.advancedtools.network.ToggleMagnetPayload;
import dev.ssscfw.advancedtools.network.ToggleSolidifierPayload;
import net.minecraft.client.Minecraft;
import net.minecraft.client.player.LocalPlayer;
import net.minecraft.world.item.ItemStack;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.client.event.ClientTickEvent;
import net.neoforged.neoforge.network.PacketDistributor;
import org.lwjgl.glfw.GLFW;

@EventBusSubscriber(modid = AdvancedTools.MOD_ID, value = Dist.CLIENT)
public final class ClientGameEvents {
    private static boolean fWasDown;

    private ClientGameEvents() {
    }

    @SubscribeEvent
    public static void onClientTick(ClientTickEvent.Pre event) {
        Minecraft minecraft = Minecraft.getInstance();
        LocalPlayer player = minecraft.player;
        if (player == null || minecraft.screen != null || !minecraft.isWindowActive()) {
            fWasDown = false;
            return;
        }

        boolean fDown = InputConstants.isKeyDown(minecraft.getWindow().getWindow(), GLFW.GLFW_KEY_F);
        if (fDown && !fWasDown && toggleHeldUtility(player)) {
            // F is vanilla's default swap-offhand key. Consume its pending click so toggling a utility
            // does not also move the held item between hands.
            while (minecraft.options.keySwapOffhand.consumeClick()) {
                // consume all clicks generated by this press
            }
        }
        fWasDown = fDown;
    }

    private static boolean toggleHeldUtility(LocalPlayer player) {
        ItemStack mainHand = player.getMainHandItem();
        if (sendToggle(mainHand)) {
            return true;
        }
        return sendToggle(player.getOffhandItem());
    }

    private static boolean sendToggle(ItemStack stack) {
        if (stack.getItem() instanceof MagnetItem) {
            PacketDistributor.sendToServer(ToggleMagnetPayload.INSTANCE);
            return true;
        }
        if (stack.getItem() instanceof SolidifierItem) {
            PacketDistributor.sendToServer(ToggleSolidifierPayload.INSTANCE);
            return true;
        }
        return false;
    }
}
